name: Deploy Frontend Service - Dev

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag a ser deployada'
        required: true
        default: 'latest'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar repositÃ³rio (usando a tag)
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.tag }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Log do Deploy
        run: |
          echo "ðŸš€ Iniciando deploy da tag: ${{ github.event.inputs.tag }}..."
          echo "âœ… Deploy do Frontend Service - Dev concluÃ­do com sucesso para a tag: ${{ github.event.inputs.tag }}."
